
# These are supported funding model platforms

github: #http://github.com/sponsors/tijuks
patreon: #@tijuks Replace with a single Patreon username
open_collective: #tijuks
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: #tijuks
liberapay: # tijuks
issuehunt: # tijuks
lfx_crowdfunding: # j with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: #tijuks
buy_me_a_coffee: # tijuks 
thanks_dev: # tijuks
custom: #http://github.com/sponsors/tijuks
l
